package Service;

import HotelService.*;
import Entidades.Personal;
import static SQLConex.Conection.getConeccion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anmijurane <miguel.andres_sic@tesco.edu.mx>
 */
public class FormAddClient extends javax.swing.JFrame {

    Personal person;
    static Connection Con;
    static PreparedStatement ps;
    static ResultSet rs;


    /**
     * Creates new form FormAddPersonal
     */
    public FormAddClient() {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtApPat = new javax.swing.JTextField();
        txtApMat = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtNumExt = new javax.swing.JTextField();
        txtNumInt = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtDelg = new javax.swing.JTextField();
        txtCP = new javax.swing.JTextField();
        txtTelLocal = new javax.swing.JTextField();
        txtTelMovil = new javax.swing.JTextField();
        cbxDepto = new javax.swing.JComboBox<>();
        cbxArea = new javax.swing.JComboBox<>();
        cbxCargo = new javax.swing.JComboBox<>();
        btn_insert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 302, -1));

        txtApPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApPatActionPerformed(evt);
            }
        });
        getContentPane().add(txtApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, 20));
        getContentPane().add(txtApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 220, -1));
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, -1));
        getContentPane().add(txtNumExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 85, -1));
        getContentPane().add(txtNumInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 85, -1));

        txtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColoniaActionPerformed(evt);
            }
        });
        getContentPane().add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 220, -1));

        txtDelg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDelgActionPerformed(evt);
            }
        });
        getContentPane().add(txtDelg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 280, -1));
        getContentPane().add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 80, -1));
        getContentPane().add(txtTelLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 180, -1));
        getContentPane().add(txtTelMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 390, 180, -1));

        getContentPane().add(cbxDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 170, -1));

        getContentPane().add(cbxArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 170, -1));

        getContentPane().add(cbxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 170, -1));

        btn_insert.setBackground(new java.awt.Color(222, 74, 16));
        btn_insert.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btn_insert.setText("REGISTRAR");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        getContentPane().add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 160, 40));

        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setText("APELLIDO PATERNO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel3.setText("APELLIDO MATERNO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel4.setText("CALLE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setText("NUM EXT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jLabel6.setText("NUM INT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel7.setText("COLONIA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jLabel8.setText("DELEGACION / MUNICIPIO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, 30));

        jLabel9.setText("C.P.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        jLabel10.setText("TEL LOCAL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel11.setText("TEL MOVIL");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddCliente.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 980, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed

        this.person = new Personal(
                txtName.getText().toUpperCase(), txtApPat.getText().toUpperCase(),
                txtApMat.getText().toUpperCase(), txtCalle.getText().toUpperCase(),
                txtNumExt.getText().toUpperCase(), txtNumInt.getText().toUpperCase(),
                txtColonia.getText().toUpperCase(), txtDelg.getText().toUpperCase(),
                txtCP.getText().toUpperCase(), txtTelLocal.getText(),
                txtTelMovil.getText(), cbxArea.getSelectedIndex(),
                cbxDepto.getSelectedIndex(), cbxCargo.getSelectedIndex());
        execurequery(person);

    }//GEN-LAST:event_btn_insertActionPerformed

    private void txtDelgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDelgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDelgActionPerformed

    private void txtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColoniaActionPerformed

    private void txtApPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApPatActionPerformed

    public void execurequery(Personal prsn) {
        System.out.println(prsn.toString());
        System.out.println(prsn.getCredencial());

        Con = getConeccion();
        PreparedStatement psmtpersonal = null;
        PreparedStatement psmtcredencial = null;

        try {
            Con.setAutoCommit(false);
            psmtpersonal = Con.prepareStatement("INSERT INTO personal("
                    + "nombre,apellido_m,apellido_p,calle,numero_ext,"
                    + "numero_int,colonia,delegacion,cp,tel_local,tel_movil,"
                    + "id_area,id_dpto,id_cargo,id_personal) VALUES ( " + prsn + ")");
            psmtpersonal.executeUpdate();

            psmtcredencial = Con.prepareStatement("INSERT INTO credencial("
                    + "id_personal,nombre,id_area,id_dpto,id_cargo,password) VALUES ("
                    + prsn.getCredencial() + ")");
            psmtcredencial.executeUpdate();

            //commit mysql
            int value = JOptionPane.showConfirmDialog(null, "¿CONFIRMAS LOS DATOS?", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            System.out.println(value);
            //SI 0; NO 1; CANCEL 2
            switch (value) {
                case 0:
                    Con.commit();
                    JOptionPane.showMessageDialog(this, "Se agrego el usuario: " +prsn.getName()+ "\nCon el ID: "+prsn.getid_Personal());
                    break;
                case 1:
                    Con.rollback();
                    JOptionPane.showMessageDialog(this, "Se aborto la operación");
                    break;                            
                default:
                    break;
            }

        } catch (SQLException ex) {
            System.err.print("ERROR: " + ex.getMessage());
            if (Con != null) {
                System.out.println("implement Rollback");
                try {
                    Con.rollback();
                } catch (SQLException e) {
                    System.out.println("No se pudo deshacer la acción: "
                            + e);
                }
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton btn_insert;
    private static javax.swing.JComboBox<String> cbxArea;
    private static javax.swing.JComboBox<String> cbxCargo;
    private static javax.swing.JComboBox<String> cbxDepto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApMat;
    private javax.swing.JTextField txtApPat;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtDelg;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumExt;
    private javax.swing.JTextField txtNumInt;
    private javax.swing.JTextField txtTelLocal;
    private javax.swing.JTextField txtTelMovil;
    // End of variables declaration//GEN-END:variables
}
