package Service;

import static SQLConex.Conection.getConeccion;
import static Service.FormAddClient.Con;
import static Service.FormAddClient.ps;
import static Service.FormAddClient.rs;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author anmijurane <miguel.andres_sic@tesco.edu.mx>
 */
public class Limpieza extends javax.swing.JFrame {

    /**
     * Creates new form Limpieza
     */
    public Limpieza() {
        initComponents();
        setLocationRelativeTo(null);
        label();
    }

    public void habitacion(String n_habitacion) {

        String categoria = null, estado = null, categoriaf, capacidad, costo, camas, estadof;

        try {
            Con = getConeccion();
            ps = Con.prepareStatement("SELECT * FROM habitacion WHERE id_habitacion = ?");
            ps.setString(1, n_habitacion);
            rs = ps.executeQuery();

            if (rs.next()) {
                categoria = rs.getString("id_categoria");
                System.out.println("categoria: " + categoria);
                estado = rs.getString("id_estado");
                System.out.println("estado: " + estado);
            }

            ps = Con.prepareStatement("SELECT * FROM categoria WHERE id_categoria = ?");
            ps.setString(1, categoria);
            rs = ps.executeQuery();

            if (rs.next()) {
                categoriaf = rs.getString("categoria");
                et_categoria.setText(categoriaf.toUpperCase());
                capacidad = rs.getString("capacidad");
                et_capacidad.setText(capacidad);
                costo = rs.getString("costo");
                et_costo.setText(costo);
                camas = rs.getString("camas");
                et_camas.setText(camas);

            }

            ps = Con.prepareStatement("SELECT * FROM estado WHERE id_estado = ?");
            ps.setString(1, estado);
            rs = ps.executeQuery();

            if (rs.next()) {
                estadof = rs.getString("nombre");
                et_estado.setText(estadof.toUpperCase());
            }

        } catch (SQLException ex) {
            Logger.getLogger(Limpieza.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void label() {
        et_categoria.setText(null);
        et_estado.setText(null);
        et_capacidad.setText(null);
        et_costo.setText(null);
        et_camas.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FLAT_NUMBER = new javax.swing.JComboBox<>();
        ROOM_NUMBER = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        et_categoria = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        et_estado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        et_capacidad = new javax.swing.JLabel();
        et_costo = new javax.swing.JLabel();
        et_camas = new javax.swing.JLabel();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FLAT_NUMBER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONA UN PISO", "1° PISO", "2° PISO", "3° PISO", "4° PISO", "5° PISO", "6° PISO", "7° PISO", "8° PISO", "9° PISO", "10° PISO" }));
        FLAT_NUMBER.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FLAT_NUMBERItemStateChanged(evt);
            }
        });
        getContentPane().add(FLAT_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 200, 40));

        ROOM_NUMBER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION" }));
        ROOM_NUMBER.setToolTipText(FLAT_NUMBER.getName());
        ROOM_NUMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROOM_NUMBERActionPerformed(evt);
            }
        });
        getContentPane().add(ROOM_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 200, 40));

        jLabel1.setText("CATEGORÍA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        et_categoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        et_categoria.setText("jLabel2");
        getContentPane().add(et_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, -1));

        jLabel2.setText("ESTADO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 60, -1));

        et_estado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        et_estado.setText("jLabel3");
        getContentPane().add(et_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel3.setText("CAPACIDAD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel4.setText("COSTO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel5.setText("CAMAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        et_capacidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        et_capacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        et_capacidad.setText("jLabel6");
        getContentPane().add(et_capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 60, -1));

        et_costo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        et_costo.setText("jLabel7");
        getContentPane().add(et_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        et_camas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        et_camas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        et_camas.setText("jLabel8");
        getContentPane().add(et_camas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GENERIC.png"))); // NOI18N
        getContentPane().add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String[] flatOne
            = {"SELECIONA UNA HABITACION", "101", "102", "103", "104", "105", "106", "107", "108",
                "109", "110"};
    String[] flatTwo
            = {"SELECIONA UNA HABITACION", "201", "202", "203", "204", "205", "206", "207", "208",
                "209", "210"};
    String[] flatTree
            = {"SELECIONA UNA HABITACION", "301", "302", "303", "304", "305", "306", "307", "308",
                "309", "310"};
    String[] flatFour
            = {"SELECIONA UNA HABITACION", "401", "402", "403", "404", "405", "406", "407", "408",
                "409", "410"};
    String[] flatFive
            = {"SELECIONA UNA HABITACION", "501", "502", "503", "504", "505", "506", "507", "508",
                "509", "510"};
    String[] flatSix
            = {"SELECIONA UNA HABITACION", "601", "602", "603", "604", "605", "606", "607", "608",
                "609", "610"};
    String[] flatSeven
            = {"SELECIONA UNA HABITACION", "701", "702", "703", "704", "705", "706", "707", "708",
                "709", "710"};
    String[] flatEight
            = {"SELECIONA UNA HABITACION", "801", "802", "803", "804", "805", "806", "807", "808",
                "809", "810"};
    String[] flatNine
            = {"SELECIONA UNA HABITACION", "901", "902", "903", "904", "905", "906", "907", "908",
                "909", "910"};
    String[] flatTen
            = {"SELECIONA UNA HABITACION", "1001", "1002", "1003", "1004", "1005", "1006", "1007", "1008",
                "1009", "1010"};


    private void FLAT_NUMBERItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FLAT_NUMBERItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            //System.out.println(FLAT_NUMBER.getSelectedIndex());
            int index = FLAT_NUMBER.getSelectedIndex();
            boolean tf = true;
            switch (index) {
                case 0:
                    tf = false;
                    break;
                case 1:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatOne));
                    tf = true;
                    break;
                case 2:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatTwo));
                    tf = true;
                    break;
                case 3:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatTree));
                    tf = true;
                    break;
                case 4:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatFour));
                    tf = true;
                    break;
                case 5:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatFive));
                    tf = true;
                    break;
                case 6:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatSix));
                    tf = true;
                    break;
                case 7:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatSeven));
                    tf = true;
                    break;
                case 8:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatEight));
                    tf = true;
                    break;
                case 9:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatNine));
                    tf = true;
                    break;
                case 10:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(flatTen));
                    tf = true;
                    break;
                default:
                    throw new AssertionError();
            }
            ROOM_NUMBER.setEnabled(tf);
        }
    }//GEN-LAST:event_FLAT_NUMBERItemStateChanged

    private void ROOM_NUMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROOM_NUMBERActionPerformed

        String rn = ROOM_NUMBER.getSelectedItem().toString();
        habitacion(rn);

    }//GEN-LAST:event_ROOM_NUMBERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Limpieza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JComboBox<String> FLAT_NUMBER;
    private javax.swing.JComboBox<String> ROOM_NUMBER;
    private javax.swing.JLabel et_camas;
    private javax.swing.JLabel et_capacidad;
    private javax.swing.JLabel et_categoria;
    private javax.swing.JLabel et_costo;
    private javax.swing.JLabel et_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
