package HotelService;

import Entidades.Habitacion;
import Entidades.RentaCliente;
import static SQLConex.Conection.getConeccion;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author anmijurane <miguel.andres_sic@tesco.edu.mx>
 */
public class InfoHabitacion extends javax.swing.JFrame {

    String name;
    int idPersonal, TypeForm;
    Habitacion habitacion;
    RentaCliente renta;

    /**
     * Creates new form InfoHabitacion
     */
    public InfoHabitacion() {
        initComponents();
        setTitle("INFORMACIÓN DE HABITACIÓN");
        setEditableJT(false);
    }

    public InfoHabitacion(String name, int idPersonal, int TypeForm) {
        initComponents();
        this.name = name;
        this.idPersonal = idPersonal;
        this.TypeForm = TypeForm;
        setEditableJT(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FLAT_NUMBER = new javax.swing.JComboBox<String>();
        ROOM_NUMBER = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jT_IdHabitacion = new javax.swing.JTextField();
        jT_Categoria = new javax.swing.JTextField();
        jT_Capacidad = new javax.swing.JTextField();
        jT_CostoxNoche = new javax.swing.JTextField();
        jT_Camas = new javax.swing.JTextField();
        jT_Estado = new javax.swing.JTextField();
        jT_NombreCompleto = new javax.swing.JTextField();
        jT_CheckIn = new javax.swing.JTextField();
        jT_CheckOut = new javax.swing.JTextField();
        jT_CostoTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FLAT_NUMBER.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        FLAT_NUMBER.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONA UN PISO", "1° PISO", "2° PISO", "3° PISO", "4° PISO", "5° PISO", "6° PISO", "7° PISO", "8° PISO", "9° PISO", "10° PISO" }));
        FLAT_NUMBER.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FLAT_NUMBERItemStateChanged(evt);
            }
        });
        getContentPane().add(FLAT_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 40));

        ROOM_NUMBER.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        ROOM_NUMBER.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ROOM_NUMBERItemStateChanged(evt);
            }
        });
        getContentPane().add(ROOM_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 210, 40));

        jLabel1.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 27, 26));
        jLabel1.setText("INFORMACIÓN DE HABITACIÓN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 370, 30));

        btnRegresar.setBackground(new java.awt.Color(222, 74, 16));
        btnRegresar.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 130, -1));

        jT_IdHabitacion.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_IdHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_IdHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 110, -1));

        jT_Categoria.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_Categoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 110, -1));

        jT_Capacidad.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_Capacidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 110, -1));

        jT_CostoxNoche.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_CostoxNoche.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_CostoxNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 110, -1));

        jT_Camas.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_Camas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_Camas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 110, -1));

        jT_Estado.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_Estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 110, -1));

        jT_NombreCompleto.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_NombreCompleto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 290, -1));

        jT_CheckIn.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_CheckIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 120, -1));

        jT_CheckOut.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_CheckOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 110, -1));

        jT_CostoTotal.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        jT_CostoTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_CostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 130, -1));

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(28, 27, 26));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NUM. HABITACIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 220, 150, -1));

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 27, 26));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CATEGORIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 160, -1));

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 27, 26));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CAPACIDAD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 150, -1));

        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(28, 27, 26));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("COSTO POR NOCHE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 190, -1));

        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(28, 27, 26));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CAMAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 130, -1));

        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(28, 27, 26));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ESTADO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 310, 140, -1));

        jLabel8.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(28, 27, 26));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NOMBRE CLIENTE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 290, -1));

        jLabel9.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(28, 27, 26));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CHECK IN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 120, -1));

        jLabel10.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(28, 27, 26));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CHECK OUT");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 110, -1));

        jLabel11.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(28, 27, 26));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("COSTO TOTAL");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 120, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GENERIC.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FLAT_NUMBERItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FLAT_NUMBERItemStateChanged
        Habitacion Flat = new Habitacion();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //System.out.println(FLAT_NUMBER.getSelectedIndex());
            int index = FLAT_NUMBER.getSelectedIndex();
            boolean tf = true;
            switch (index) {
                case 0:
                    tf = false;
                    break;
                case 1:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatOne()));
                    tf = true;
                    break;
                case 2:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatTwo()));
                    tf = true;
                    break;
                case 3:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatTree()));
                    tf = true;
                    break;
                case 4:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatFour()));
                    tf = true;
                    break;
                case 5:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatFive()));
                    tf = true;
                    break;
                case 6:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatSix()));
                    tf = true;
                    break;
                case 7:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatSeven()));
                    tf = true;
                    break;
                case 8:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatEight()));
                    tf = true;
                    break;
                case 9:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatNine()));
                    tf = true;
                    break;
                case 10:
                    ROOM_NUMBER.setModel(new DefaultComboBoxModel<>(Flat.getFlatTen()));
                    tf = true;
                    break;
                default:
                    throw new AssertionError();
            }
            FLAT_NUMBER.setEnabled(tf);
        }
    }//GEN-LAST:event_FLAT_NUMBERItemStateChanged

    private void ROOM_NUMBERItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ROOM_NUMBERItemStateChanged
        getDataHabitacion(ROOM_NUMBER.getSelectedItem());
        getClienteInfo(ROOM_NUMBER.getSelectedItem());
    }//GEN-LAST:event_ROOM_NUMBERItemStateChanged

    public void getDataHabitacion(Object idHabitacion) {
        Connection Con = getConeccion();
        PreparedStatement infoHabitacion;
        ResultSet rsHabitacion;

        String sqlInfoHab = "select habitacion.id_habitacion, categoria.categoria, categoria.capacidad, categoria.costo, categoria.camas, estado.nombre"
                + " FROM habitacion, categoria, estado"
                + " WHERE id_habitacion = " + idHabitacion
                + " AND categoria.id_categoria = habitacion.id_categoria"
                + " AND estado.id_estado = habitacion.id_estado";

        try {
            infoHabitacion = Con.prepareStatement(sqlInfoHab);
            //System.out.println(infoHabitacion);
            rsHabitacion = infoHabitacion.executeQuery();

            if (rsHabitacion.next()) {

                habitacion = new Habitacion(
                        rsHabitacion.getInt(1),
                        rsHabitacion.getString(2),
                        rsHabitacion.getString(3),
                        rsHabitacion.getInt(5),
                        rsHabitacion.getString(6));
                habitacion.setCosto(rsHabitacion.getDouble(4));
                LlenarDatosHabitacion();
            } else {
                JOptionPane.showMessageDialog(this, "¡UY!, OCURRIO UN ERROR");
            }

        } catch (SQLException e) {
            System.out.println("ERROR METOD GET DATA: " + e);
        }
    }

    public void LlenarDatosHabitacion() {

        jT_IdHabitacion.setText("" + habitacion.getId_habitacion());
        jT_Categoria.setText(habitacion.getCategoria());
        jT_Capacidad.setText(habitacion.getCapacidad());
        jT_CostoxNoche.setText(habitacion.getCosto());
        jT_Camas.setText("" + habitacion.getCamas());
        jT_Estado.setText(habitacion.getEstado());

    }

    public void LlenarDatosCliente() {

        jT_NombreCompleto.setText(renta.getNombreCompleto());
        jT_CheckIn.setText("" + renta.getEntrada());
        jT_CheckOut.setText(renta.getSalida());
        jT_CostoTotal.setText(renta.CalcularCosto());

    }

    public void getClienteInfo(Object idHabitacion) {
        LimpiarDatosCliente();
        Connection Con = getConeccion();
        PreparedStatement clientInfo;
        ResultSet rsCliente;

        String sqlInfoClint = "select renta.id_habitacion, cliente.nombre, cliente.apellido_p, cliente.apellido_m, renta.id_cliente, \n"
                + "renta.personas, renta.entrada, renta.salida, renta.costo_renta, renta.id_metpago from renta\n"
                + " INNER JOIN cliente ON renta.id_cliente = cliente.id_cliente\n"
                + " WHERE renta.id_habitacion = " + idHabitacion;
        try {

            clientInfo = Con.prepareStatement(sqlInfoClint);
            //System.out.println(clientInfo);            
            rsCliente = clientInfo.executeQuery();

            if (rsCliente.next()) {
                /*renta = new RentaCliente(
                        rsCliente.getInt(1),
                        rsCliente.getInt(5));*/

                renta = new RentaCliente(
                        rsCliente.getInt(1),
                        rsCliente.getInt(5),
                        rsCliente.getString(2),
                        rsCliente.getString(3),
                        rsCliente.getString(4),
                        rsCliente.getInt(6),
                        rsCliente.getDate(7),
                        rsCliente.getDouble(9));
                renta.setMetdPago(rsCliente.getInt(10));

                String salidaE = rsCliente.getString(8);
                System.out.println("SALIDA: " + salidaE);

                if (salidaE.equals("0000-00-00")) {
                    renta.setSalida("AL DIA");
                } else {
                    renta.setSalida(salidaE);
                }
                LlenarDatosCliente();

            } else {
                jT_NombreCompleto.setText("NO ASIGNADO");
                jT_CheckIn.setText("");
                jT_CheckOut.setText("");
                jT_CostoTotal.setText("$ 000.00");
            }

        } catch (SQLException e) {
            System.out.println("ERROR EN getClienteInfo: " + e);
        }
    }

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        switch (TypeForm) {
            case 2:
                new MenuRecepcionista(name, idPersonal).setVisible(true);
                this.dispose();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void LimpiarDatosHabitacion() {
        jT_IdHabitacion.setText("");
        jT_Capacidad.setText("");
        jT_Categoria.setText("");
        jT_CostoxNoche.setText("");
        jT_Camas.setText("");
        jT_Estado.setText("");
    }

    public void LimpiarDatosCliente() {
        jT_NombreCompleto.setText("");
        jT_CheckIn.setText("");
        jT_CheckOut.setText("");
        jT_CostoTotal.setText("");
    }

    public void setEditableJT(boolean statusFlag) {
        jT_Camas.setEditable(statusFlag);
        jT_Capacidad.setEditable(statusFlag);
        jT_Categoria.setEditable(statusFlag);
        jT_CheckIn.setEditable(statusFlag);
        jT_CheckOut.setEditable(statusFlag);
        jT_CostoTotal.setEditable(statusFlag);
        jT_CostoxNoche.setEditable(statusFlag);
        jT_Estado.setEditable(statusFlag);
        jT_IdHabitacion.setEditable(statusFlag);
        jT_NombreCompleto.setEditable(statusFlag);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FLAT_NUMBER;
    private javax.swing.JComboBox<String> ROOM_NUMBER;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jT_Camas;
    private javax.swing.JTextField jT_Capacidad;
    private javax.swing.JTextField jT_Categoria;
    private javax.swing.JTextField jT_CheckIn;
    private javax.swing.JTextField jT_CheckOut;
    private javax.swing.JTextField jT_CostoTotal;
    private javax.swing.JTextField jT_CostoxNoche;
    private javax.swing.JTextField jT_Estado;
    private javax.swing.JTextField jT_IdHabitacion;
    private javax.swing.JTextField jT_NombreCompleto;
    // End of variables declaration//GEN-END:variables
}

/* CONSULTA DE INFORMACION DE HABITACIÓN
select habitacion.id_habitacion, categoria.categoria, categoria.capacidad, categoria.costo, categoria.camas, estado.nombre
    FROM habitacion, categoria, estado    
    WHERE id_habitacion = 202
    AND categoria.id_categoria = habitacion.id_categoria
    AND estado.id_estado = habitacion.id_estado;
    
    CONSULTA DE USUARIO EN LA HABITACIÓN
select renta.id_habitacion, cliente.nombre, cliente.apellido_p, cliente.apellido_m, renta.id_cliente, 
renta.personas, renta.entrada, renta.salida, renta.costo_renta, renta.id_metpago from renta
INNER JOIN cliente ON renta.id_cliente = cliente.id_cliente
WHERE renta.id_habitacion = 202;

 */
