/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelService;

import Service.FormAddClient;

/**
 *
 * @author Montzerrat Rivera
 */
public class MenuGerencia extends javax.swing.JFrame {
    private String name;
    private int idPersonal;
    /**
     * Creates new form MenuGerencia
     * @param name
     * @param idPersonal
     */
    public MenuGerencia(String name, int idPersonal) {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("MENU GERENCIA");
        this.name = name;
        this.idPersonal = idPersonal;
        jT_Tittle.setText("HOLA " +name+", ¿QUÉ DESEAS HACER? ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegistrarUsr = new javax.swing.JButton();
        btnInfoHab = new javax.swing.JButton();
        btnRentarHab = new javax.swing.JButton();
        btnConsultarServ = new javax.swing.JButton();
        btnAddUsuario = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jT_Tittle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 36)); // NOI18N
        jLabel2.setText("GERENCIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnRegistrarUsr.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnRegistrarUsr.setText("REGISTRAR UN USUARIO");
        btnRegistrarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsrActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 260, 40));

        btnInfoHab.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnInfoHab.setText("INFO DE HABITACIÓN");
        btnInfoHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 260, 40));

        btnRentarHab.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnRentarHab.setText("RENTAR UNA HABITACIÓN");
        btnRentarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentarHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnRentarHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 260, 40));

        btnConsultarServ.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnConsultarServ.setText("CONSULTAR SERVICIO");
        btnConsultarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarServActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 240, 40));

        btnAddUsuario.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        btnAddUsuario.setText("AÑADIR USUARIO");
        btnAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 240, 40));

        jButton6.setBackground(new java.awt.Color(222, 74, 16));
        jButton6.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jButton6.setText("CERRAR SESIÓN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 520, 190, 40));

        jT_Tittle.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jT_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jT_Tittle.setText("HOLA");
        getContentPane().add(jT_Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 490, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GENERIC.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnRegistrarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsrActionPerformed
        new FormAddClient(name, idPersonal, 1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarUsrActionPerformed

    private void btnInfoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoHabActionPerformed
        new InfoHabitacion(name, idPersonal, 1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInfoHabActionPerformed

    private void btnRentarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentarHabActionPerformed
        new RentarHabitacion(name, idPersonal,1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRentarHabActionPerformed

    private void btnConsultarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarServActionPerformed
        new Servicio_limpiezaMANT(name, idPersonal).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarServActionPerformed

    private void btnAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUsuarioActionPerformed
        new FormAddPersonal(name, idPersonal).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddUsuarioActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUsuario;
    private javax.swing.JButton btnConsultarServ;
    private javax.swing.JButton btnInfoHab;
    private javax.swing.JButton btnRegistrarUsr;
    private javax.swing.JButton btnRentarHab;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jT_Tittle;
    // End of variables declaration//GEN-END:variables
}
