/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelService;

import Entidades.Habitacion;
import Entidades.Paquete;
import static SQLConex.Conection.getConeccion;
import Service.FormAddClient;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author anmijurane <miguel.andres_sic@tesco.edu.mx>
 */
public class RentarHabitacion extends javax.swing.JFrame {

    Connection Con = getConeccion();
    PreparedStatement ps;
    ResultSet rs;
    int idCliente;
    int idPersona;
    String name;
    Paquete pack;

    /**
     * Creates new form RentarHabitacion
     *
     * @param name
     * @param idPersonal
     */
    public RentarHabitacion(String name, int idPersonal) {
        initComponents();
        getNameClient();
        setModelSpinner();
        this.idPersona = idPersonal;
        this.name = name;
        cleanPanel(false);
        //btn_back.setVisible(true);
    }

    public final void getNameClient() {
        try {

            cbxClient.addItem("ELIGE UN CLIENTE");

            ps = Con.prepareStatement("SELECT id_cliente, nombre, apellido_p, apellido_m FROM cliente ORDER BY apellido_p ASC");
            rs = ps.executeQuery();

            while (rs.next()) {
                cbxClient.addItem(rs.getString("apellido_p") + " " + rs.getString("apellido_m") + " " + rs.getString("nombre"));
                idCliente = rs.getInt("id_cliente");
            }

        } catch (SQLException e) {
            System.out.println("ERROR EN " + e);
        }
    }

    public void ObtenerDatos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegCliente = new javax.swing.JButton();
        cbxClient = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        check_in = new com.toedter.calendar.JDateChooser();
        check_out = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jCbx_NumHab = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCbx_01 = new javax.swing.JComboBox<>();
        jP_Hab_01 = new javax.swing.JSpinner();
        jP_Hab_02 = new javax.swing.JSpinner();
        jP_Hab_03 = new javax.swing.JSpinner();
        jP_Hab_04 = new javax.swing.JSpinner();
        jP_Hab_05 = new javax.swing.JSpinner();
        jP_Hab_06 = new javax.swing.JSpinner();
        jP_Hab_07 = new javax.swing.JSpinner();
        jP_Hab_08 = new javax.swing.JSpinner();
        jP_Hab_09 = new javax.swing.JSpinner();
        jP_Hab_010 = new javax.swing.JSpinner();
        jCbx_02 = new javax.swing.JComboBox<>();
        jCbx_03 = new javax.swing.JComboBox<>();
        jCbx_04 = new javax.swing.JComboBox<>();
        jCbx_05 = new javax.swing.JComboBox<>();
        jCbx_06 = new javax.swing.JComboBox<>();
        jCbx_07 = new javax.swing.JComboBox<>();
        jCbx_08 = new javax.swing.JComboBox<>();
        jCbx_09 = new javax.swing.JComboBox<>();
        jCbx_010 = new javax.swing.JComboBox<>();
        jLHab1 = new javax.swing.JLabel();
        jLHab4 = new javax.swing.JLabel();
        jLHab3 = new javax.swing.JLabel();
        jLHab2 = new javax.swing.JLabel();
        jLHab5 = new javax.swing.JLabel();
        jLHab9 = new javax.swing.JLabel();
        jLHab8 = new javax.swing.JLabel();
        jLHab7 = new javax.swing.JLabel();
        jLHab6 = new javax.swing.JLabel();
        jLHab10 = new javax.swing.JLabel();
        Precio1 = new javax.swing.JLabel();
        Precio2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        btnRegCliente.setText("REGISTRAR CLIENTE");
        btnRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegClienteActionPerformed(evt);
            }
        });

        cbxClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel1.setText("CLIENTE:");

        check_in.setBackground(new java.awt.Color(255, 153, 51));

        check_out.setBackground(new java.awt.Color(255, 153, 51));

        jLabel2.setText("CHECK-IN");

        jLabel3.setText("CHECK-OUT");

        btn_back.setText("REGRESAR");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jCbx_NumHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Núm Habitaciones", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jCbx_NumHab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCbx_NumHab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbx_NumHabItemStateChanged(evt);
            }
        });

        jLabel4.setText("HABITACIONES");

        jCbx_01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));
        jCbx_01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCbx_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_01ActionPerformed(evt);
            }
        });

        jP_Hab_01.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_01StateChanged(evt);
            }
        });

        jP_Hab_02.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_02StateChanged(evt);
            }
        });

        jP_Hab_03.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_03StateChanged(evt);
            }
        });

        jP_Hab_04.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_04StateChanged(evt);
            }
        });

        jP_Hab_05.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_05StateChanged(evt);
            }
        });

        jP_Hab_06.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_06StateChanged(evt);
            }
        });

        jP_Hab_07.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_07StateChanged(evt);
            }
        });

        jP_Hab_08.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_08StateChanged(evt);
            }
        });

        jP_Hab_09.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_09StateChanged(evt);
            }
        });

        jP_Hab_010.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jP_Hab_010StateChanged(evt);
            }
        });

        jCbx_02.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_03.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_04.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_05.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_06.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_07.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_08.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_09.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jCbx_010.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONA UNA HABITACION", "INDIVIDUAL", "JUNIOR SUITE" }));

        jLHab1.setText("Habitacion 1:");

        jLHab4.setText("Habitacion 4:");

        jLHab3.setText("Habitacion 3:");

        jLHab2.setText("Habitacion 2:");

        jLHab5.setText("Habitacion 5:");

        jLHab9.setText("Habitacion 9:");

        jLHab8.setText("Habitacion 8:");

        jLHab7.setText("Habitacion 7:");

        jLHab6.setText("Habitacion 6:");

        jLHab10.setText("Habitacion 10:");

        Precio1.setText("Precio $");

        Precio2.setText("Precio $");

        jButton1.setText("GO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jP_Hab_05, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbx_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(297, 297, 297)
                        .addComponent(btn_back)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLHab1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxClient, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(72, 72, 72)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jCbx_NumHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Precio1)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jP_Hab_03, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jP_Hab_01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(jP_Hab_02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jCbx_02, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCbx_01, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCbx_03, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLHab2))
                                        .addComponent(jLHab4)
                                        .addComponent(jLHab5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jP_Hab_04, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCbx_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLHab3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(50, 50, 50))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Precio2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(check_out, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLHab9)
                                                            .addComponent(jP_Hab_010, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jP_Hab_09, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(13, 13, 13))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jP_Hab_06, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                    .addComponent(jP_Hab_07, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                                    .addComponent(jP_Hab_08, javax.swing.GroupLayout.Alignment.LEADING)))
                                                            .addComponent(jLHab6))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jCbx_06, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jCbx_07, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jCbx_09, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jCbx_08, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jCbx_010, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addComponent(check_in, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLHab10)
                                                    .addComponent(jLHab8)
                                                    .addComponent(jLHab7))))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField6)
                                            .addComponent(jTextField7)
                                            .addComponent(jTextField8)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                                .addContainerGap(47, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_NumHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHab1)
                            .addComponent(jLHab6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Precio2)
                            .addComponent(Precio1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbx_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jP_Hab_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jP_Hab_06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHab2)
                            .addComponent(jLHab7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jP_Hab_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jP_Hab_07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHab3)
                            .addComponent(jLHab8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jP_Hab_03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jP_Hab_08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHab4)
                            .addComponent(jLHab9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jP_Hab_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jP_Hab_09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHab5)
                            .addComponent(jLHab10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jP_Hab_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jP_Hab_010, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_010, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(btnRegCliente)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegClienteActionPerformed
        new FormAddClient(name, idPersona, 5).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegClienteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new MenuRecepcionista(name, idPersona).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void jCbx_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_01ActionPerformed

    }//GEN-LAST:event_jCbx_01ActionPerformed

    private void jP_Hab_01StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_01StateChanged
        jCbx_01.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_01.getValue())));
    }//GEN-LAST:event_jP_Hab_01StateChanged

    private void jP_Hab_02StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_02StateChanged
        jCbx_02.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_02.getValue())));
    }//GEN-LAST:event_jP_Hab_02StateChanged

    private void jP_Hab_03StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_03StateChanged
        jCbx_03.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_03.getValue())));
    }//GEN-LAST:event_jP_Hab_03StateChanged

    private void jP_Hab_04StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_04StateChanged
        jCbx_04.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_04.getValue())));
    }//GEN-LAST:event_jP_Hab_04StateChanged

    private void jP_Hab_05StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_05StateChanged
        jCbx_05.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_05.getValue())));
    }//GEN-LAST:event_jP_Hab_05StateChanged

    private void jP_Hab_06StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_06StateChanged
        jCbx_06.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_06.getValue())));
    }//GEN-LAST:event_jP_Hab_06StateChanged

    private void jP_Hab_07StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_07StateChanged
        jCbx_07.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_07.getValue())));
    }//GEN-LAST:event_jP_Hab_07StateChanged

    private void jP_Hab_08StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_08StateChanged
        jCbx_08.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_08.getValue())));
    }//GEN-LAST:event_jP_Hab_08StateChanged

    private void jP_Hab_09StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_09StateChanged
        jCbx_09.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_09.getValue())));
    }//GEN-LAST:event_jP_Hab_09StateChanged

    private void jP_Hab_010StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jP_Hab_010StateChanged
        jCbx_010.setModel(new DefaultComboBoxModel<>(new Habitacion().getCategoria(jP_Hab_010.getValue())));
    }//GEN-LAST:event_jP_Hab_010StateChanged

    public final void cleanPanel(boolean value) {
        jP_Hab_01.setVisible(value);
        jP_Hab_02.setVisible(value);
        jP_Hab_03.setVisible(value);
        jP_Hab_04.setVisible(value);
        jP_Hab_05.setVisible(value);
        jP_Hab_06.setVisible(value);
        jP_Hab_07.setVisible(value);
        jP_Hab_08.setVisible(value);
        jP_Hab_09.setVisible(value);
        jP_Hab_010.setVisible(value);
        jCbx_01.setVisible(value);
        jCbx_02.setVisible(value);
        jCbx_03.setVisible(value);
        jCbx_04.setVisible(value);
        jCbx_05.setVisible(value);
        jCbx_06.setVisible(value);
        jCbx_07.setVisible(value);
        jCbx_08.setVisible(value);
        jCbx_09.setVisible(value);
        jCbx_010.setVisible(value);
        jLHab1.setVisible(value);
        jLHab2.setVisible(value);
        jLHab3.setVisible(value);
        jLHab4.setVisible(value);
        jLHab5.setVisible(value);
        jLHab6.setVisible(value);
        jLHab7.setVisible(value);
        jLHab8.setVisible(value);
        jLHab9.setVisible(value);
        jLHab10.setVisible(value);
        jTextField1.setVisible(value);
        jTextField2.setVisible(value);
        jTextField3.setVisible(value);
        jTextField4.setVisible(value);
        jTextField5.setVisible(value);
        jTextField6.setVisible(value);
        jTextField7.setVisible(value);
        jTextField8.setVisible(value);
        jTextField9.setVisible(value);
        jTextField10.setVisible(value);
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
        Precio1.setVisible(value);
        Precio2.setVisible(value);
    }

    private void jCbx_NumHabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbx_NumHabItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            cleanPanel(false);
            int valor = jCbx_NumHab.getSelectedIndex();
            switch (valor) {
                case 0:
                    JOptionPane.showMessageDialog(this, "AL MENOS DEBE EXISTIR UNA HABITACIÓN");
                    jCbx_NumHab.setSelectedIndex(1);
                    jP_Hab_01.setVisible(true);
                    jCbx_01.setVisible(true);
                    jLHab1.setVisible(true);
                    Precio1.setVisible(true);
                    break;
                case 1:
                    Precio1.setVisible(true);
                    jP_Hab_01.setVisible(true);
                    jCbx_01.setVisible(true);
                    jLHab1.setVisible(true);
                    jTextField1.setVisible(true);
                    break;
                case 2:
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);

                    break;
                case 3:
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);
                    jP_Hab_03.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);
                    jCbx_03.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);
                    jLHab3.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);

                    break;
                case 4:
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);
                    jP_Hab_03.setVisible(true);
                    jP_Hab_04.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);
                    jCbx_03.setVisible(true);
                    jCbx_04.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);
                    jLHab3.setVisible(true);
                    jLHab4.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);

                    break;
                case 5:
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);
                    jP_Hab_03.setVisible(true);
                    jP_Hab_04.setVisible(true);
                    jP_Hab_05.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);
                    jCbx_03.setVisible(true);
                    jCbx_04.setVisible(true);
                    jCbx_05.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);
                    jLHab3.setVisible(true);
                    jLHab4.setVisible(true);
                    jLHab5.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jTextField5.setVisible(true);

                    break;
                case 6:
                    Precio2.setVisible(true);
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);
                    jP_Hab_03.setVisible(true);
                    jP_Hab_04.setVisible(true);
                    jP_Hab_05.setVisible(true);
                    jP_Hab_06.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);
                    jCbx_03.setVisible(true);
                    jCbx_04.setVisible(true);
                    jCbx_05.setVisible(true);
                    jCbx_06.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);
                    jLHab3.setVisible(true);
                    jLHab4.setVisible(true);
                    jLHab5.setVisible(true);
                    jLHab6.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jTextField5.setVisible(true);
                    jTextField6.setVisible(true);

                    break;
                case 7:
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);
                    jP_Hab_03.setVisible(true);
                    jP_Hab_04.setVisible(true);
                    jP_Hab_05.setVisible(true);
                    jP_Hab_06.setVisible(true);
                    jP_Hab_07.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);
                    jCbx_03.setVisible(true);
                    jCbx_04.setVisible(true);
                    jCbx_05.setVisible(true);
                    jCbx_06.setVisible(true);
                    jCbx_07.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);
                    jLHab3.setVisible(true);
                    jLHab4.setVisible(true);
                    jLHab5.setVisible(true);
                    jLHab6.setVisible(true);
                    jLHab7.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jTextField5.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField7.setVisible(true);

                    break;
                case 8:
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);
                    jP_Hab_03.setVisible(true);
                    jP_Hab_04.setVisible(true);
                    jP_Hab_05.setVisible(true);
                    jP_Hab_06.setVisible(true);
                    jP_Hab_07.setVisible(true);
                    jP_Hab_08.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);
                    jCbx_03.setVisible(true);
                    jCbx_04.setVisible(true);
                    jCbx_05.setVisible(true);
                    jCbx_06.setVisible(true);
                    jCbx_07.setVisible(true);
                    jCbx_08.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);
                    jLHab3.setVisible(true);
                    jLHab4.setVisible(true);
                    jLHab5.setVisible(true);
                    jLHab6.setVisible(true);
                    jLHab7.setVisible(true);
                    jLHab8.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jTextField5.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField7.setVisible(true);
                    jTextField8.setVisible(true);

                    break;
                case 9:
                    jP_Hab_01.setVisible(true);
                    jP_Hab_02.setVisible(true);
                    jP_Hab_03.setVisible(true);
                    jP_Hab_04.setVisible(true);
                    jP_Hab_05.setVisible(true);
                    jP_Hab_06.setVisible(true);
                    jP_Hab_07.setVisible(true);
                    jP_Hab_08.setVisible(true);
                    jP_Hab_09.setVisible(true);

                    jCbx_01.setVisible(true);
                    jCbx_02.setVisible(true);
                    jCbx_03.setVisible(true);
                    jCbx_04.setVisible(true);
                    jCbx_05.setVisible(true);
                    jCbx_06.setVisible(true);
                    jCbx_07.setVisible(true);
                    jCbx_08.setVisible(true);
                    jCbx_09.setVisible(true);

                    jLHab1.setVisible(true);
                    jLHab2.setVisible(true);
                    jLHab3.setVisible(true);
                    jLHab4.setVisible(true);
                    jLHab5.setVisible(true);
                    jLHab6.setVisible(true);
                    jLHab7.setVisible(true);
                    jLHab8.setVisible(true);
                    jLHab9.setVisible(true);

                    jTextField1.setVisible(true);
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jTextField5.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField7.setVisible(true);
                    jTextField8.setVisible(true);
                    jTextField9.setVisible(true);

                    break;
                case 10:
                    cleanPanel(true);
                    break;

                default:
                    throw new AssertionError();
            }
        }
    }//GEN-LAST:event_jCbx_NumHabItemStateChanged

    public final void setModelSpinner() {
        jP_Hab_01.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_010.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_02.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_03.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_04.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_05.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_06.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_07.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_08.setModel(new SpinnerNumberModel(1, 1, 4, 1));
        jP_Hab_09.setModel(new SpinnerNumberModel(1, 1, 4, 1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentarHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Precio1;
    private javax.swing.JLabel Precio2;
    private javax.swing.JButton btnRegCliente;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> cbxClient;
    private com.toedter.calendar.JDateChooser check_in;
    private com.toedter.calendar.JDateChooser check_out;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCbx_01;
    private javax.swing.JComboBox<String> jCbx_010;
    private javax.swing.JComboBox<String> jCbx_02;
    private javax.swing.JComboBox<String> jCbx_03;
    private javax.swing.JComboBox<String> jCbx_04;
    private javax.swing.JComboBox<String> jCbx_05;
    private javax.swing.JComboBox<String> jCbx_06;
    private javax.swing.JComboBox<String> jCbx_07;
    private javax.swing.JComboBox<String> jCbx_08;
    private javax.swing.JComboBox<String> jCbx_09;
    private javax.swing.JComboBox<String> jCbx_NumHab;
    private javax.swing.JLabel jLHab1;
    private javax.swing.JLabel jLHab10;
    private javax.swing.JLabel jLHab2;
    private javax.swing.JLabel jLHab3;
    private javax.swing.JLabel jLHab4;
    private javax.swing.JLabel jLHab5;
    private javax.swing.JLabel jLHab6;
    private javax.swing.JLabel jLHab7;
    private javax.swing.JLabel jLHab8;
    private javax.swing.JLabel jLHab9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jP_Hab_01;
    private javax.swing.JSpinner jP_Hab_010;
    private javax.swing.JSpinner jP_Hab_02;
    private javax.swing.JSpinner jP_Hab_03;
    private javax.swing.JSpinner jP_Hab_04;
    private javax.swing.JSpinner jP_Hab_05;
    private javax.swing.JSpinner jP_Hab_06;
    private javax.swing.JSpinner jP_Hab_07;
    private javax.swing.JSpinner jP_Hab_08;
    private javax.swing.JSpinner jP_Hab_09;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}

//select habitacion.id_habitacion, categoria.capacidad, categoria.costo 
//FROM habitacion INNER JOIN categoria ON habitacion.id_categoria = categoria.id_categoria;
